### ISSUE TITLE
script output does not match with steamlit app

### ISSUE THREAD

**Issue by shantanuo** [arindamsaha1507/sankhyaakaara#13]
when I execute python file numerals.py I get the output that does not seem to be correct. For e.g.

Enter a number without commas: 2424
{'s': 'चतुर्विंशति-उत्तर-अयुत-शत-उत्तर-शत-सहस्रम्'}

This does not match with the output of steamlit app

https://sankhya.streamlit.app/ 

चतुर्विंशत्यधिकचतुश्शताधिकद्विसहस्रम्

Even after considering the sandhi, the output is completely different.

**Comment by shantanuo** [comment]
Instead of running only numerals.py if I run the steamlit application command (streamlit run app.py) then the output match and it means that the code has no issues. Thank you for this open source project. It is helping me a lot to understand Sanskrit. But I am trying to run the number to text function without user interface. Is it possible?

**Comment by shantanuo** [comment]
If I add this line to converter.py file then I get the text that I was looking for.

print(Converter().get_word(2424))

Using converter.py file instead of numerals.py was the answer. Thanks for this awesome code. Closing the issue.

**Comment by arindamsaha1507** [comment]
Hi @shantanuo,

Thanks a lot for the interest! I see that you have resolved the issue yourself! Nice!

I originally made this app in a hurry... so did not pay much attention to the code organisation.

I did not expect many users to use it :stuck_out_tongue: 

However, seeing that some people (around 2.5k) use it, do you think it will be useful as a python package too (similar to [akshara](https://pypi.org/project/akshara/)?

P.S. If you enjoyed this app, you might also like the new [Sanskrit Wordle](https://sanskrit-wordle.streamlit.app/) app that I recently created. :smile:

**Comment by shantanuo** [comment]
Yes. In fact, python package is more useful than streamlit app.

**Comment by arindamsaha1507** [comment]
OK... Let me work on that :smile: 

Opening a new issue for that
