### ISSUE TITLE
Create python package

### ISSUE THREAD

**Issue by arindamsaha1507** [arindamsaha1507/sankhyaakaara#15]

**Comment by arindamsaha1507** [comment]
Requested by @shantanuo

**Comment by arindamsaha1507** [comment]
Hi @shantanuo,


Please try installing and using the sankhyaakaara package from pip.

I have added the usage guidelines in the README.

Let me know if you are able to use it.

**Comment by shantanuo** [comment]
Yes. It is working as per my expectations. Thanks for your quick response. By the way this looks like an awesome project.
