### ISSUE TITLE
number_input instead of text?

### ISSUE THREAD

**Issue by thakkaha** [arindamsaha1507/sankhyaakaara#9]
uttamam! @arindamsaha1507 

i am new to streamlit ... but was wondering, (after looking at some if/else) - can we replace line 15 in app.py 

`query = st.text_input("Please enter a number")` 
with
`query = st.number_input("Please enter a number", min_value=0, step=1)` ?

**Comment by arindamsaha1507** [comment]
Thanks @thakkaha 

I myself like `number_input()`.

However, the `max_value` that it accepts is approx. 10^15 which is less than the 10^18 numbers that can be named :D

This limit is seemingly put by JavaScript... :( 
See this 

https://chat.openai.com/share/bcdfd633-546f-470e-99c1-4a939b708889

But the code is much cleaner with`number_input()`. Plus more people seem to like interface of `number_input()`.

What do you suggest? Should we go for the `number_input()`?

**Comment by thakkaha** [comment]
yes @arindamsaha1507 - let's try `number_input()` then 👍 dhanyavaadaH

**Comment by arindamsaha1507** [comment]
Done 👍✅
